version: "2"

linters:
  default: none
  enable:
    - staticcheck
    - gosec
    - govet
    - ineffassign
    - unused
  settings:
    gosec:
      excludes:
        - G301
        - G304
        - G306

  exclusions:
    paths:
      - vendor
      - dashboard
      - widget
      - docs
      - gen
      - maree
    rules:
      - path: "(.+)_test\\.go"
        linters:
          - gosec
